/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author guilh
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bordaJava = new javax.swing.JInternalFrame();
        barraFerramentas = new javax.swing.JToolBar();
        b_Inicio = new javax.swing.JButton();
        b_Ajuda = new javax.swing.JButton();
        painelConverte = new javax.swing.JPanel();
        t_converteDe = new javax.swing.JLabel();
        painelPara = new javax.swing.JPanel();
        t_Para = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valorSaida = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        valorEntrada = new javax.swing.JTextPane();
        variavelConverte = new javax.swing.JComboBox<>();
        variavelPara = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bordaJava.setVisible(true);

        barraFerramentas.setRollover(true);

        b_Inicio.setText("Inicio");
        b_Inicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_Inicio.setFocusable(false);
        b_Inicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_Inicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFerramentas.add(b_Inicio);

        b_Ajuda.setText("Ajuda");
        b_Ajuda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_Ajuda.setFocusable(false);
        b_Ajuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_Ajuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFerramentas.add(b_Ajuda);

        painelConverte.setBackground(new java.awt.Color(208, 250, 255));
        painelConverte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        t_converteDe.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        t_converteDe.setText("Converte de:");

        javax.swing.GroupLayout painelConverteLayout = new javax.swing.GroupLayout(painelConverte);
        painelConverte.setLayout(painelConverteLayout);
        painelConverteLayout.setHorizontalGroup(
            painelConverteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConverteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t_converteDe)
                .addGap(22, 22, 22))
        );
        painelConverteLayout.setVerticalGroup(
            painelConverteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConverteLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(t_converteDe)
                .addGap(46, 46, 46))
        );

        painelPara.setBackground(new java.awt.Color(208, 250, 255));
        painelPara.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        t_Para.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        t_Para.setText("Para:");

        javax.swing.GroupLayout painelParaLayout = new javax.swing.GroupLayout(painelPara);
        painelPara.setLayout(painelParaLayout);
        painelParaLayout.setHorizontalGroup(
            painelParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelParaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(t_Para)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelParaLayout.setVerticalGroup(
            painelParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelParaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(t_Para)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        valorSaida.setEditable(false);
        valorSaida.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        valorSaida.setFocusable(false);
        jScrollPane1.setViewportView(valorSaida);

        valorEntrada.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        jScrollPane2.setViewportView(valorEntrada);

        variavelConverte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", " " }));

        variavelPara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout bordaJavaLayout = new javax.swing.GroupLayout(bordaJava.getContentPane());
        bordaJava.getContentPane().setLayout(bordaJavaLayout);
        bordaJavaLayout.setHorizontalGroup(
            bordaJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraFerramentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bordaJavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bordaJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelConverte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(bordaJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(variavelConverte, 0, 238, Short.MAX_VALUE)
                    .addComponent(variavelPara, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(bordaJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bordaJavaLayout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(290, Short.MAX_VALUE)))
        );
        bordaJavaLayout.setVerticalGroup(
            bordaJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bordaJavaLayout.createSequentialGroup()
                .addGroup(bordaJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bordaJavaLayout.createSequentialGroup()
                        .addComponent(barraFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelConverte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bordaJavaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(variavelConverte, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(bordaJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bordaJavaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bordaJavaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bordaJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(variavelPara, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
            .addGroup(bordaJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bordaJavaLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(172, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bordaJava)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bordaJava)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Ajuda;
    private javax.swing.JButton b_Inicio;
    private javax.swing.JToolBar barraFerramentas;
    private javax.swing.JInternalFrame bordaJava;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelConverte;
    private javax.swing.JPanel painelPara;
    private javax.swing.JLabel t_Para;
    private javax.swing.JLabel t_converteDe;
    private javax.swing.JTextPane valorEntrada;
    private javax.swing.JTextPane valorSaida;
    private javax.swing.JComboBox<String> variavelConverte;
    private javax.swing.JComboBox<String> variavelPara;
    // End of variables declaration//GEN-END:variables
}
